name: Deliver Tokens To Consumer

on:
  push:
    paths:
      - 'build/scss/**'

jobs:
  # Add a job for every additional consumer/application
    deliver_to_react_application:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Deliver Platform Deliverable To Application
          uses: andstor/copycat-action@v3
          with:
            # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
            # Set the secret in the "src" repository
            personal_token: ${{ secrets.API_TOKEN_GITHUB }}
            # This is the branch that has the code for this article
            src_branch: main
            src_path: build/scss/_variables.scss
            dst_owner: aqweider
            dst_repo_name: consume-style-dictionary
            dst_branch: main
            dst_path: tokens/_variables.scss
            username: aqweider
            email: attallah.qweider@gmail.com
            commit_message: Update platform deliverable