name: Generate Tokens On Input

on:
  push:
    paths:
      - 'tokens/design-tokens.json'

jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          username: aqweider
          email: attallah.qweider@gmail.com
          commit_message: Update design tokens